<a href="https://colab.research.google.com/github/Joniald/Colaboratory/blob/main/Notes_on_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import tensorflow as tf
import numpy as np

## Cross-validation

Scikit-Learn’s K-fold cross-validation feature. The following code randomly splits the training set into 10 distinct subsets called folds, then it
trains and evaluates the model 10 times, picking a different fold for evaluation every time and training on the other 9 folds. 
The result is an array containing the 10 evaluation scores:

In [21]:
from sklearn.model_selection import cross_val_score

In [1]:
from sklearn.model_selection import cross_val_predict

Just like the cross_val_score() function, cross_val_predict() performs K-fold
cross-validation, but instead of returning the evaluation scores, it returns the predictions
made on each test fold.

## Accuracy

The accuracy is the proportion of correct predictions (both true positives and true negatives) among the total number of cases examined.

Accuracy is generally not the preferred performance measure for classifiers, especially when you are dealing with skewed datasets 
(i.e., when some classes are much more frequent than others).

$accuracy = \frac{TP+FN}{TP+FN+FP+TN}$

In [22]:
from sklearn.metrics import accuracy_score

## Persition, Recall

True positives are data points classified as positive by the model that actually are positive (meaning they are correct). (TP)
False negatives are data points the model identifies as negative that actually are positive (incorrect). (FN)
False positives are cases the model incorrectly labels as positive that are actually negative. (FP)
True negative cases the model incorrectly labels as negative that are actually positive. (TN)

$persition = \frac{TP}{TP+FP}$

$recall = \frac{TP}{TP+FN}$

In [23]:
from sklearn.metrics import precision_score, recall_score

## F1-score

The F1 score favors classifiers that have similar precision and recall. This is not always 
what you want: in some contexts you mostly care about precision, and in other contexts
you really care about recall. For example, if you trained a classifier to detect videos
that are safe for kids, you would probably prefer a classifier that rejects many
good videos (low recall) but keeps only safe ones (high precision), rather than a classifier
that has a much higher recall but lets a few really bad videos show up in your
product (in such cases, you may even want to add a human pipeline to check the classifier’s
video selection). On the other hand, suppose you train a classifier to detect
shoplifters in surveillance images: it is probably fine if your classifier has only 30%
precision as long as it has 99% recall (sure, the security guards will get a few false
alerts, but almost all shoplifters will get caught).

$F1 = 2*\frac{persition*recall}{persition+recall}$

In [24]:
from sklearn.metrics import f1_score

## Confusion Matrix

A much better way to evaluate the performance of a classifier is to look at the confusion
matrix. The general idea is to count the number of times instances of class A are
classified as class B.

In [25]:
from sklearn.metrics import confusion_matrix

In [26]:
# Sklearn

y_train = [1,1,0,0,1,0,0,1,1,1,0,0,1,0,1,0,1,0,0,0,0]
y_predict = [0,1,0,1,1,1,0,1,0,1,0,0,0,1,0,0,1,0,1,0,1]

print(accuracy_score(y_train, y_predict))
print(precision_score(y_train, y_predict))
print(recall_score(y_train, y_predict))
print(f1_score(y_train, y_predict))
print(confusion_matrix(y_train, y_predict))
             

0.5714285714285714
0.5
0.5555555555555556
0.5263157894736842
[[7 5]
 [4 5]]


In [27]:
# TensorFlow

y_train = [1,1,0,0,1,0,0,1,1,1,0,0,1,0,1,0,1,0,0,0,0]
y_predict = [0,1,0,1,1,1,0,1,0,1,0,0,0,1,0,0,1,0,1,0,1]

m = tf.keras.metrics.Precision()
m.update_state(y_train, y_predict)
m.result().numpy()

0.5

# Models

In [7]:
from sklearn.linear_model import SGDClassifier

In [8]:
from sklearn.linear_model import SGDRegressor

In [6]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit([[0, 0], [1, 1], [2, 2]], [0, 1, 2])
reg.predict([[3,3]])

array([3.])

In [9]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
from sklearn.ensemble import RandomForestRegressor

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor

In [12]:
from sklearn.ensemble import RandomForestRegressor
regr = RandomForestRegressor(max_depth=2, random_state=0)

In [5]:
from sklearn.svm import SVC
svm_model = SVC()
svm_model.fit([[0, 0], [1, 1], [2, 2]], [0, 1, 2])
svm_model.predict([[3,3]])

array([2])

In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor

## Multiclass Classification

SGD classifiers, Random Forest classifiers, and naive Bayes classifiers are capable of handling multiple classes natively.
Logistic Regression or Support Vector Machine classifiers are strictly binary classifiers. 
However, there are various strategies that you can use to perform multiclass classification with multiple binary classifiers.

The one-versus-the-rest (OvR) strategy.
The one-versus-one (OvO) strategy

Scikit-Learn detects when you try to use a binary classification algorithm for a multiclass classification task, and it automatically runs OvR or OvO, depending on the algorithm.